/* tslint:disable */
/* eslint-disable */
/**
 * Dittofeed API
 * Interactive API documentation.
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AppsBatchBody
 */
export interface AppsBatchBody {
    /**
     * 
     * @type {any}
     * @memberof AppsBatchBody
     */
    batch: any;
    /**
     * 
     * @type {any}
     * @memberof AppsBatchBody
     */
    context?: any;
}
