global:
  scrape_interval: 15s # Scrape metrics every 15 seconds
scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889', 'otel-collector:8888']
