FROM temporalio/auto-setup:1.22

COPY render/temporal/server/dynamicconfig.yaml /etc/temporal/dynamicconfig.yaml
# COPY render/temporal/server/config_template.yaml /etc/temporal/config/config_template.yaml
# COPY render/temporal/server/auto-setup/auto-setup-override.sh /etc/temporal/auto-setup.sh
# COPY render/temporal/server/.bashrc /home/temporal/.bashrc
