app = 'diitofeed-api'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2

[[mounts]]
    destination = "/data"
    source = "data_staging"
    initial_size = "1GB"
    auto_extend_size_threshold = 80
    auto_extend_size_increment = "1GB"
    auto_extend_size_limit = "5GB"