# Default values for dittofeed.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ee:
  enabled: false

# This configuration disables the worker in our primary deployment, which then
# only runs the API and Dashboard. We then create separate worker deployments
# for each of the temporal queues utilized by Dittofeed.
separateWorker:
  enabled: true
  worker:
    image:
      repository: harbor.gbinfra.io/dittofeed/dittofeed-worker
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: "6bad241"

  # The default queue is used to process user journeys.
  default:
    replicaCount: 3
    maxOldSpaceSize: 4096
    resources:
      limits:
        cpu: 8
        memory: 6Gi
      requests:
        cpu: 1
        memory: 1024Mi
  # The workspace queue is used to recompute workspaces' segments and user properties, and to process broadcasts.
  workspace:
    replicaCount: 3
    maxOldSpaceSize: 4096
    resources:
      limits:
        cpu: 8
        memory: 6Gi
      requests:
        cpu: 1
        memory: 2048Mi
  # Is used to handle secondary scheduled workflows.
  global:
    replicaCount: 3
    maxOldSpaceSize: 4096
    resources:
      limits:
        cpu: 8
        memory: 6Gi
      requests:
        cpu: 1
        memory: 1024Mi

  transactional:
    replicaCount: 3
    maxOldSpaceSize: 4096
    resources:
      limits:
        cpu: 8
        memory: 6Gi
      requests:
        cpu: 1
        memory: 1024Mi
    additional_env:
      - name: USER_JOURNEY_TASK_QUEUE
        value: "default"
      - name: TRANSACTIONAL_TASK_QUEUE
        value: "transactional"

workspaceName: Dittofeed
replicaCount: 3

maxOldSpaceSize: 4096

image:
  repository: harbor.gbinfra.io/dittofeed/dittofeed-lite
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "6bad241"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns-prod
  hosts:
    - host: dittofeed-dev.hngcweywe.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: dittofeed-dev-hngcweywe-com-tls
     hosts:
       - dittofeed-dev.hngcweywe.com

ingress_public_api:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns-prod
  hosts:
    - host: api-dt-dev.hngcweywe.com
      paths:
        - path: /api/public/subscription-management/page
          pathType: Prefix
  tls:
   - secretName: api-dt-hngcweywe-com-tls
     hosts:
       - api-dt-dev.hngcweywe.com
  dashboard_api_base: https://dittofeed-dev.hngcweywe.com

resources:
  # Recommended resources for production
  limits:
    cpu: 8
    memory: 6Gi
  requests:
    cpu: 1
    memory: 512Mi

clickhouse:
  # Enable to install ClickHouse as a dependency
  enabled: false
  # Minimal installation for ease of testing.
  shards: 1
  replicaCount: 1
  zookeeper:
    enabled: false
  defaultConfigurationOverrides: |
    <clickhouse>
      <macros>
        <shard>1</shard>
        <replica>single</replica>
      </macros>
    </clickhouse>
  resources:
    limits:
      memory: 1024Mi
    requests:
      memory: 1024Mi
  auth:
    username: dittofeed
    password: password
    database: dittofeed
    # uncomment to use an existing secret for the password
    # existingSecret: "my-clickhouse-secret-name"
    # existingSecretKey: "password"

postgresql:
  # Enable to install PostgreSQL as a dependency
  enabled: false
  auth:
    username: postgres
    password: password
    database: dittofeed
    # uncomment to use an existing secret for the password
    # existingSecret: "my-pg-secret-name"
    # userPasswordKey: "password"

temporal:
  # Enable to install standalone Temporal as a dependency
  enabled: false
  resources: {}
    # limits:
    #   cpu: 1
    #   memory: 1024Mi
    # requests:
    #   cpu: 1
    #   memory: 1024Mi
  env:
    - name: POSTGRES_SEEDS
      value: "demo-postgresql.default.svc.cluster.local"
    - name: POSTGRES_USER
      value: "postgres"
    - name: POSTGRES_PWD
      value: "password"

  image:
    repository: temporalio/auto-setup
    tag: 1.23.1.0
    pullPolicy: IfNotPresent

env:
  - name: START_OTEL
    value: "false"
  - name: OTEL_COLLECTOR
    value: "http://jaeger-collector.jaeger.svc.cluster.local:4317"
  - name: DATABASE_HOST
    value: "postgresql-dittofeed-dev-cluster-pgbouncer.dittofeed-dev.svc.cluster.local"
  - name: DATABASE_USER
    value: "dittofeed"
  - name: DATABASE_PASSWORD
    value: "a9v0wWPc9OCcLYd7Zy4wSXxR0vIoOk6y8sTGwbuJeMj5iyeUdfPN0bWsLlBUBuvE"
  ## - name: DATABASE_PASSWORD
  #   valueFrom:
  #     secretKeyRef:
  #       name: my-pg-secret-name
  #       key: password
  - name: CLICKHOUSE_HOST
    value: "http://clickhouse-clickhouse-dittofeed-dev.dittofeed-dev.svc.cluster.local:8123"
  - name: CLICKHOUSE_USER
    value: "dittofeed"
  - name: CLICKHOUSE_PASSWORD
    value: "54u6tdi7fkyhgcmfyxhtdzgrdtf"
  # - name: CLICKHOUSE_PASSWORD
  #   valueFrom:
  #     secretKeyRef:
  #       name: my-clickhouse-secret-name
  #       key: password
  # BOOTSTRAP should be set to "false" after the first deployment
  - name: BOOTSTRAP
    value: "false"
  - name: BOOTSTRAP_SAFE
    value: "false"
  - name: TEMPORAL_ADDRESS
    value: "dittofeed-temporal-frontend.dittofeed-dev.svc.cluster.local:7233"
  - name: AUTH_MODE
    value: "single-tenant"   # уже выставляется chart'ом для lite
  - name: PASSWORD
    value: "dqk3bqe0thx*dwk-EDH"   # или secretKeyRef
  - name: SECRET_KEY
    value: "yOG2b51bouPH3gcmNKGkq0F1ErKaBcRqBiLpYHCX8sQ="   # openssl rand -base64 32
  - name: SESSION_COOKIE_SECURE
    value: "true"
# necessary to use the write mode
  - name: WRITE_MODE
    value: kafka
# the kafka host and portnames to write to
  - name: KAFKA_BROKERS
    value: "dittofeed-dev-kafka-kafka-brokers:9092"
# the username and password to use for the kafka connection
  - name: KAFKA_USERNAME
    value: dittofeed-dev
  - name: KAFKA_PASSWORD
    value: "axm6qhg_HMX5zqr1wty"
# whether to use SSL for the kafka connection
  - name: KAFKA_SSL
    value: "false"
# the kafka sasl mechanism to use
# possible values are: plain, scram-sha-256, scram-sha-512
  - name: KAFKA_SASL_MECHANISM
    value: "scram-sha-512"
# the number of partitions to use for the user events topic when bootstrapping
  - name: KAFKA_USER_EVENTS_PARTITIONS
    value: "3"
# the replication factor to use for the user events topic when bootstrapping
  - name: KAFKA_USER_EVENTS_REPLICATION_FACTOR
    value: "3"
# the name of the user events topic to create when bootstrapping
  - name: USER_EVENTS_TOPIC_NAME
    value: dittofeed-user-events
  - name: MAX_CACHED_WORKFLOWS
    value: "1000"
  - name: MAX_CONCURRENT_WORKFLOW_TASK_POLLS
    value: "150"
  - name: MAX_CONCURRENT_ACTIVITY_TASK_POLLS
    value: "150"
  - name: MAX_CONCURRENT_WORKFLOW_TASK_EXECUTIONS
    value: "240"
  - name: MAX_CONCURRENT_ACTIVITY_TASK_EXECUTIONS
    value: "1000"
  - name: REUSE_CONTEXT
    value: "true"
  - name: COMPUTE_PROPERTIES_TIMEOUT
    value: "900000"
  - name: CLICKHOUSE_COMPUTE_PROPERTIES_REQUEST_TIMEOUT
    value: "180000"
  - name: COMPUTE_PROPERTIES_QUEUE_CONCURRENCY
    value: "10"
  - name: SKIP_PRUNE_JSON_EXISTS
    value: "true"
  - name: COMPUTE_PROPERTIES_INTERVAL
    value: "5000"
  - name: COMPUTE_PROPERTIES_SCHEDULER_INTERVAL
    value: "1000"
  - name: COMPUTE_PROPERTIES_JITTER_MS
    value: "0"
  - name: CLICKHOUSE_MAX_MEMORY_USAGE
    value: "161061273600"
  - name: COMPUTED_PROPERTIES_TASK_QUEUE
    value: "workspace"
  - name: COMPUTED_PROPERTIES_ACTIVITY_TASK_QUEUE
    value: "workspace"
  - name: COMPUTE_PROPERTIES_SPLIT
    value: "true"
  - name: "WRITE_COMPUTED_PROPERTY_ASSIGNMENTS_CURRENT"
    value: "true"
  - name: "READ_COMPUTED_PROPERTY_ASSIGNMENTS_FROM_CURRENT"
    value: "true"
  - name: "REALTIME_SEGMENTS_ENABLED"
    value: "true"
  - name: "REALTIME_SEGMENTS_MODE"
    value: "true"
  - name: "REALTIME_SEGMENTS_QUEUE_BACKEND"
    value: "true"
  - name: "REALTIME_SEGMENTS_NATS_SERVERS"
    value: "nats://nats.dittofeed.svc.cluster.local:4222"
  - name: "REALTIME_SEGMENTS_NATS_USERNAME"
    value: "app"
  - name: "REALTIME_SEGMENTS_NATS_PASSWORD"
    value: "wym4udp*YPA7het4bzr"
nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: workload
          operator: In
          values:
          - "true"


livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 1
  failureThreshold: 5
  successThreshold: 1
  httpGet:
    path: /api
    port: 3000

