/* tslint:disable */
/* eslint-disable */
/**
 * Twenty Api
 * This is a **Twenty REST/API** playground based on the **OpenAPI 3.1 specification**.
 *
 * The version of the OpenAPI document: v0.1
 * Contact: felix@twenty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CompanyForResponseCreatedBy } from './company-for-response-created-by';
// May contain unused imports in some cases
// @ts-ignore
import type { ObjeGct } from './obje-gct';
// May contain unused imports in some cases
// @ts-ignore
import type { PersonEmails } from './person-emails';
// May contain unused imports in some cases
// @ts-ignore
import type { PersonLinkedinLink } from './person-linkedin-link';
// May contain unused imports in some cases
// @ts-ignore
import type { PersonName } from './person-name';
// May contain unused imports in some cases
// @ts-ignore
import type { PersonPhones } from './person-phones';
// May contain unused imports in some cases
// @ts-ignore
import type { PersonXLink } from './person-xlink';

/**
 * A person
 * @export
 * @interface PersonForResponse
 */
export interface PersonForResponse {
    /**
     * 
     * @type {PersonName}
     * @memberof PersonForResponse
     */
    'name'?: PersonName;
    /**
     * 
     * @type {string}
     * @memberof PersonForResponse
     */
    'companyId'?: string;
    /**
     * Date when the record was deleted
     * @type {string}
     * @memberof PersonForResponse
     */
    'deletedAt'?: string;
    /**
     * Last time the record was changed
     * @type {string}
     * @memberof PersonForResponse
     */
    'updatedAt'?: string;
    /**
     * Creation date
     * @type {string}
     * @memberof PersonForResponse
     */
    'createdAt'?: string;
    /**
     * Id
     * @type {string}
     * @memberof PersonForResponse
     */
    'id'?: string;
    /**
     * 
     * @type {CompanyForResponseCreatedBy}
     * @memberof PersonForResponse
     */
    'createdBy'?: CompanyForResponseCreatedBy;
    /**
     * Person record Position
     * @type {number}
     * @memberof PersonForResponse
     */
    'position'?: number;
    /**
     * Contact’s avatar
     * @type {string}
     * @memberof PersonForResponse
     */
    'avatarUrl'?: string;
    /**
     * Contact’s city
     * @type {string}
     * @memberof PersonForResponse
     */
    'city'?: string;
    /**
     * 
     * @type {PersonPhones}
     * @memberof PersonForResponse
     */
    'phones'?: PersonPhones;
    /**
     * Contact’s job title
     * @type {string}
     * @memberof PersonForResponse
     */
    'jobTitle'?: string;
    /**
     * 
     * @type {PersonXLink}
     * @memberof PersonForResponse
     */
    'xLink'?: PersonXLink;
    /**
     * 
     * @type {PersonLinkedinLink}
     * @memberof PersonForResponse
     */
    'linkedinLink'?: PersonLinkedinLink;
    /**
     * 
     * @type {PersonEmails}
     * @memberof PersonForResponse
     */
    'emails'?: PersonEmails;
    /**
     * 
     * @type {object}
     * @memberof PersonForResponse
     */
    'company'?: object;
    /**
     * List of opportunities for which that person is the point of contact
     * @type {Array<object>}
     * @memberof PersonForResponse
     */
    'pointOfContactForOpportunities'?: Array<object>;
    /**
     * Tasks tied to the contact
     * @type {Array<object>}
     * @memberof PersonForResponse
     */
    'taskTargets'?: Array<object>;
    /**
     * Notes tied to the contact
     * @type {Array<object>}
     * @memberof PersonForResponse
     */
    'noteTargets'?: Array<object>;
    /**
     * Attachments linked to the contact.
     * @type {Array<object>}
     * @memberof PersonForResponse
     */
    'attachments'?: Array<object>;
    /**
     * Favorites linked to the contact
     * @type {Array<object>}
     * @memberof PersonForResponse
     */
    'favorites'?: Array<object>;
    /**
     * Message Participants
     * @type {Array<ObjeGct>}
     * @memberof PersonForResponse
     */
    'messageParticipants'?: Array<ObjeGct>;
    /**
     * Calendar Event Participants
     * @type {Array<object>}
     * @memberof PersonForResponse
     */
    'calendarEventParticipants'?: Array<object>;
    /**
     * Events linked to the person
     * @type {Array<object>}
     * @memberof PersonForResponse
     */
    'timelineActivities'?: Array<object>;
}

