/* tslint:disable */
/* eslint-disable */
/**
 * Twenty Api
 * This is a **Twenty REST/API** playground based on the **OpenAPI 3.1 specification**.
 *
 * The version of the OpenAPI document: v0.1
 * Contact: felix@twenty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PersonCreatedPostRequestObjectMetadata } from './person-created-post-request-object-metadata';
// May contain unused imports in some cases
// @ts-ignore
import type { PersonForResponse } from './person-for-response';

/**
 * 
 * @export
 * @interface PersonCreatedPostRequest
 */
export interface PersonCreatedPostRequest {
    /**
     * 
     * @type {string}
     * @memberof PersonCreatedPostRequest
     */
    'targetUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonCreatedPostRequest
     */
    'eventName'?: string;
    /**
     * 
     * @type {PersonCreatedPostRequestObjectMetadata}
     * @memberof PersonCreatedPostRequest
     */
    'objectMetadata'?: PersonCreatedPostRequestObjectMetadata;
    /**
     * 
     * @type {string}
     * @memberof PersonCreatedPostRequest
     */
    'workspaceId'?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonCreatedPostRequest
     */
    'webhookId'?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonCreatedPostRequest
     */
    'eventDate'?: string;
    /**
     * 
     * @type {PersonForResponse}
     * @memberof PersonCreatedPostRequest
     */
    'record'?: PersonForResponse;
}

