/* tslint:disable */
/* eslint-disable */
/**
 * Twenty Api
 * This is a **Twenty REST/API** playground based on the **OpenAPI 3.1 specification**.
 *
 * The version of the OpenAPI document: v0.1
 * Contact: felix@twenty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CalendarEventConferenceLinkSecondaryLinksInner } from './calendar-event-conference-link-secondary-links-inner';

/**
 * Contact’s Linkedin account
 * @export
 * @interface PersonLinkedinLink
 */
export interface PersonLinkedinLink {
    /**
     * 
     * @type {string}
     * @memberof PersonLinkedinLink
     */
    'primaryLinkLabel'?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonLinkedinLink
     */
    'primaryLinkUrl'?: string;
    /**
     * 
     * @type {Array<CalendarEventConferenceLinkSecondaryLinksInner>}
     * @memberof PersonLinkedinLink
     */
    'secondaryLinks'?: Array<CalendarEventConferenceLinkSecondaryLinksInner>;
}

