/* tslint:disable */
/* eslint-disable */
/**
 * Twenty Api
 * This is a **Twenty REST/API** playground based on the **OpenAPI 3.1 specification**.
 *
 * The version of the OpenAPI document: v0.1
 * Contact: felix@twenty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Contact’s name
 * @export
 * @interface PersonName
 */
export interface PersonName {
    /**
     * 
     * @type {string}
     * @memberof PersonName
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonName
     */
    'lastName'?: string;
}

