/* tslint:disable */
/* eslint-disable */
/**
 * Twenty Api
 * This is a **Twenty REST/API** playground based on the **OpenAPI 3.1 specification**.
 *
 * The version of the OpenAPI document: v0.1
 * Contact: felix@twenty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Contact’s phone numbers
 * @export
 * @interface PersonPhones
 */
export interface PersonPhones {
    /**
     * 
     * @type {Array<string>}
     * @memberof PersonPhones
     */
    'additionalPhones'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PersonPhones
     */
    'primaryPhoneCountryCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonPhones
     */
    'primaryPhoneCallingCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonPhones
     */
    'primaryPhoneNumber'?: string;
}

