/* tslint:disable */
/* eslint-disable */
/**
 * Twenty Api
 * This is a **Twenty REST/API** playground based on the **OpenAPI 3.1 specification**.
 *
 * The version of the OpenAPI document: v0.1
 * Contact: felix@twenty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CompanyCreatedBy } from './company-created-by';
// May contain unused imports in some cases
// @ts-ignore
import type { PersonEmails } from './person-emails';
// May contain unused imports in some cases
// @ts-ignore
import type { PersonLinkedinLink } from './person-linkedin-link';
// May contain unused imports in some cases
// @ts-ignore
import type { PersonName } from './person-name';
// May contain unused imports in some cases
// @ts-ignore
import type { PersonPhones } from './person-phones';
// May contain unused imports in some cases
// @ts-ignore
import type { PersonXLink } from './person-xlink';

/**
 * A person
 * @export
 * @interface Person
 */
export interface Person {
    /**
     * 
     * @type {PersonName}
     * @memberof Person
     */
    'name'?: PersonName;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    'companyId'?: string;
    /**
     * 
     * @type {CompanyCreatedBy}
     * @memberof Person
     */
    'createdBy'?: CompanyCreatedBy;
    /**
     * Person record Position
     * @type {number}
     * @memberof Person
     */
    'position'?: number;
    /**
     * Contact’s avatar
     * @type {string}
     * @memberof Person
     */
    'avatarUrl'?: string;
    /**
     * Contact’s city
     * @type {string}
     * @memberof Person
     */
    'city'?: string;
    /**
     * 
     * @type {PersonPhones}
     * @memberof Person
     */
    'phones'?: PersonPhones;
    /**
     * Contact’s job title
     * @type {string}
     * @memberof Person
     */
    'jobTitle'?: string;
    /**
     * 
     * @type {PersonXLink}
     * @memberof Person
     */
    'xLink'?: PersonXLink;
    /**
     * 
     * @type {PersonLinkedinLink}
     * @memberof Person
     */
    'linkedinLink'?: PersonLinkedinLink;
    /**
     * 
     * @type {PersonEmails}
     * @memberof Person
     */
    'emails'?: PersonEmails;
}

