limit.maxIDLength:
  - value: 255
    constraints: {}
system.forceSearchAttributesCacheRefreshOnRead:
  - value: true # Dev setup only. Please don't turn this on in production.
    constraints: {}

# Enable archival uncommented when using blob-storage
# Archival configuration
# history.archival.enabled:
#   - value: true
#     constraints: {}
# history.archival.enableReadFromArchival:
#   - value: true
#     constraints: {}
# visibility.archival.enabled:
#   - value: true
#     constraints: {}
# visibility.archival.enableReadFromArchival:
#   - value: true
#     constraints: {}

# # Configure archival URIs for the default namespace
# # For MinIO/blob-storage use:
# namespace.archival.history.state:
#   - value: "enabled"
#     constraints:
#       namespace: "default"
# namespace.archival.history.URI:
#   - value: "s3://dittofeed/temporal-archival/history?endpoint=blob-storage:9000&s3ForcePathStyle=true"
#     constraints:
#       namespace: "default"
# namespace.archival.visibility.state:
#   - value: "enabled"
#     constraints:
#       namespace: "default"
# namespace.archival.visibility.URI:
#   - value: "s3://dittofeed/temporal-archival/visibility?endpoint=blob-storage:9000&s3ForcePathStyle=true"
#     constraints:
#       namespace: "default"
