limit.maxIDLength:
  - value: 255
    constraints: {}

# Uncomment to enable archival (requires S3 bucket access)
# Archival configuration for production
# history.archival.enabled:
#   - value: true
#     constraints: {}
# history.archival.enableReadFromArchival:
#   - value: true
#     constraints: {}
# visibility.archival.enabled:
#   - value: true
#     constraints: {}
# visibility.archival.enableReadFromArchival:
#   - value: true
#     constraints: {}

# # Configure archival URIs for the default namespace  
# namespace.archival.history.state:
#   - value: "enabled"
#     constraints:
#       namespace: "default"
# namespace.archival.history.URI:
#   - value: "s3://dittofeed/temporal-archival/history"
#     constraints:
#       namespace: "default"
# namespace.archival.visibility.state:
#   - value: "enabled"
#     constraints:
#       namespace: "default"
# namespace.archival.visibility.URI:
#   - value: "s3://dittofeed/temporal-archival/visibility"
#     constraints:
#       namespace: "default"
