limit.maxIDLength:
  - value: 255
    constraints: {}

# Enable archival: use ARCHIVAL_HISTORY_STATE and ARCHIVAL_VISIBILITY_STATE env vars instead
# Configure archival URIs for the default namespace  
# namespace.archival.history.state:
#   - value: "enabled"
#     constraints:
#       namespace: "default"
# namespace.archival.history.URI:
#   - value: "s3://dittofeed/temporal-archival/history"
#     constraints:
#       namespace: "default"
# namespace.archival.visibility.state:
#   - value: "enabled"
#     constraints:
#       namespace: "default"
# namespace.archival.visibility.URI:
#   - value: "s3://dittofeed/temporal-archival/visibility"
#     constraints:
#       namespace: "default"
