/* tslint:disable */
/* eslint-disable */
/**
 * Twenty Api
 * This is a **Twenty REST/API** playground based on the **OpenAPI 3.1 specification**.
 *
 * The version of the OpenAPI document: v0.1
 * Contact: felix@twenty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreateOneField200ResponseData } from './create-one-field200-response-data';

/**
 * 
 * @export
 * @interface CreateOneField200Response
 */
export interface CreateOneField200Response {
    /**
     * 
     * @type {CreateOneField200ResponseData}
     * @memberof CreateOneField200Response
     */
    'data'?: CreateOneField200ResponseData;
}

