/* tslint:disable */
/* eslint-disable */
/**
 * Twenty Api
 * This is a **Twenty REST/API** playground based on the **OpenAPI 3.1 specification**.
 *
 * The version of the OpenAPI document: v0.1
 * Contact: felix@twenty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DeleteOneObject200ResponseDataDeleteOneObject } from './delete-one-object200-response-data-delete-one-object';

/**
 * 
 * @export
 * @interface DeleteOneField200ResponseData
 */
export interface DeleteOneField200ResponseData {
    /**
     * 
     * @type {DeleteOneObject200ResponseDataDeleteOneObject}
     * @memberof DeleteOneField200ResponseData
     */
    'deleteOneField'?: DeleteOneObject200ResponseDataDeleteOneObject;
}

