/* tslint:disable */
/* eslint-disable */
/**
 * Twenty Api
 * This is a **Twenty REST/API** playground based on the **OpenAPI 3.1 specification**.
 *
 * The version of the OpenAPI document: v0.1
 * Contact: felix@twenty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DeleteOneField200ResponseData } from './delete-one-field200-response-data';

/**
 * 
 * @export
 * @interface DeleteOneField200Response
 */
export interface DeleteOneField200Response {
    /**
     * 
     * @type {DeleteOneField200ResponseData}
     * @memberof DeleteOneField200Response
     */
    'data'?: DeleteOneField200ResponseData;
}

