/* tslint:disable */
/* eslint-disable */
/**
 * Twenty Api
 * This is a **Twenty REST/API** playground based on the **OpenAPI 3.1 specification**.
 *
 * The version of the OpenAPI document: v0.1
 * Contact: felix@twenty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FieldsIdGet200ResponseData } from './fields-id-get200-response-data';

/**
 * 
 * @export
 * @interface FieldsIdGet200Response
 */
export interface FieldsIdGet200Response {
    /**
     * 
     * @type {FieldsIdGet200ResponseData}
     * @memberof FieldsIdGet200Response
     */
    'data'?: FieldsIdGet200ResponseData;
}

