/* tslint:disable */
/* eslint-disable */
/**
 * Twenty Api
 * This is a **Twenty REST/API** playground based on the **OpenAPI 3.1 specification**.
 *
 * The version of the OpenAPI document: v0.1
 * Contact: felix@twenty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FieldsGet200ResponseData } from './fields-get200-response-data';
// May contain unused imports in some cases
// @ts-ignore
import type { ObjectsGet200ResponsePageInfo } from './objects-get200-response-page-info';

/**
 * 
 * @export
 * @interface FieldsGet200Response
 */
export interface FieldsGet200Response {
    /**
     * 
     * @type {FieldsGet200ResponseData}
     * @memberof FieldsGet200Response
     */
    'data'?: FieldsGet200ResponseData;
    /**
     * 
     * @type {ObjectsGet200ResponsePageInfo}
     * @memberof FieldsGet200Response
     */
    'pageInfo'?: ObjectsGet200ResponsePageInfo;
}

