/* tslint:disable */
/* eslint-disable */
/**
 * Twenty Api
 * This is a **Twenty REST/API** playground based on the **OpenAPI 3.1 specification**.
 *
 * The version of the OpenAPI document: v0.1
 * Contact: felix@twenty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FieldOptionsInner
 */
export interface FieldOptionsInner {
    /**
     * 
     * @type {string}
     * @memberof FieldOptionsInner
     */
    'color'?: string;
    /**
     * 
     * @type {string}
     * @memberof FieldOptionsInner
     */
    'label'?: string;
    /**
     * 
     * @type {string}
     * @memberof FieldOptionsInner
     */
    'value'?: string;
    /**
     * 
     * @type {number}
     * @memberof FieldOptionsInner
     */
    'position'?: number;
}

