/* tslint:disable */
/* eslint-disable */
/**
 * Twenty Api
 * This is a **Twenty REST/API** playground based on the **OpenAPI 3.1 specification**.
 *
 * The version of the OpenAPI document: v0.1
 * Contact: felix@twenty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FieldOptionsInner } from './field-options-inner';

/**
 * A field
 * @export
 * @interface FieldForUpdate
 */
export interface FieldForUpdate {
    /**
     * 
     * @type {string}
     * @memberof FieldForUpdate
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof FieldForUpdate
     */
    'label'?: string;
    /**
     * 
     * @type {string}
     * @memberof FieldForUpdate
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof FieldForUpdate
     */
    'icon'?: string;
    /**
     * 
     * @type {any}
     * @memberof FieldForUpdate
     */
    'defaultValue'?: any;
    /**
     * 
     * @type {boolean}
     * @memberof FieldForUpdate
     */
    'isNullable'?: boolean;
    /**
     * 
     * @type {object}
     * @memberof FieldForUpdate
     */
    'settings'?: object;
    /**
     * For enum field types like SELECT or MULTI_SELECT
     * @type {Array<FieldOptionsInner>}
     * @memberof FieldForUpdate
     */
    'options'?: Array<FieldOptionsInner>;
}

