/* tslint:disable */
/* eslint-disable */
/**
 * Twenty Api
 * This is a **Twenty REST/API** playground based on the **OpenAPI 3.1 specification**.
 *
 * The version of the OpenAPI document: v0.1
 * Contact: felix@twenty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetOpenApiSchema200ResponseInfoContact } from './get-open-api-schema200-response-info-contact';
// May contain unused imports in some cases
// @ts-ignore
import type { GetOpenApiSchema200ResponseInfoLicense } from './get-open-api-schema200-response-info-license';

/**
 * 
 * @export
 * @interface GetOpenApiSchema200ResponseInfo
 */
export interface GetOpenApiSchema200ResponseInfo {
    /**
     * 
     * @type {string}
     * @memberof GetOpenApiSchema200ResponseInfo
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOpenApiSchema200ResponseInfo
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOpenApiSchema200ResponseInfo
     */
    'termsOfService'?: string;
    /**
     * 
     * @type {GetOpenApiSchema200ResponseInfoContact}
     * @memberof GetOpenApiSchema200ResponseInfo
     */
    'contact'?: GetOpenApiSchema200ResponseInfoContact;
    /**
     * 
     * @type {GetOpenApiSchema200ResponseInfoLicense}
     * @memberof GetOpenApiSchema200ResponseInfo
     */
    'license'?: GetOpenApiSchema200ResponseInfoLicense;
}

