/* tslint:disable */
/* eslint-disable */
/**
 * Twenty Api
 * This is a **Twenty REST/API** playground based on the **OpenAPI 3.1 specification**.
 *
 * The version of the OpenAPI document: v0.1
 * Contact: felix@twenty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetOpenApiSchema200ResponseComponents } from './get-open-api-schema200-response-components';
// May contain unused imports in some cases
// @ts-ignore
import type { GetOpenApiSchema200ResponseInfo } from './get-open-api-schema200-response-info';

/**
 * 
 * @export
 * @interface GetOpenApiSchema200Response
 */
export interface GetOpenApiSchema200Response {
    /**
     * 
     * @type {string}
     * @memberof GetOpenApiSchema200Response
     */
    'openapi'?: string;
    /**
     * 
     * @type {GetOpenApiSchema200ResponseInfo}
     * @memberof GetOpenApiSchema200Response
     */
    'info'?: GetOpenApiSchema200ResponseInfo;
    /**
     * 
     * @type {Array<any>}
     * @memberof GetOpenApiSchema200Response
     */
    'servers'?: Array<any>;
    /**
     * 
     * @type {GetOpenApiSchema200ResponseComponents}
     * @memberof GetOpenApiSchema200Response
     */
    'components'?: GetOpenApiSchema200ResponseComponents;
    /**
     * 
     * @type {object}
     * @memberof GetOpenApiSchema200Response
     */
    'paths'?: object;
    /**
     * 
     * @type {object}
     * @memberof GetOpenApiSchema200Response
     */
    'tags'?: object;
}

