/* tslint:disable */
/* eslint-disable */
/**
 * Twenty Api
 * This is a **Twenty REST/API** playground based on the **OpenAPI 3.1 specification**.
 *
 * The version of the OpenAPI document: v0.1
 * Contact: felix@twenty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ObjectsGet200ResponsePageInfo
 */
export interface ObjectsGet200ResponsePageInfo {
    /**
     * 
     * @type {boolean}
     * @memberof ObjectsGet200ResponsePageInfo
     */
    'hasNextPage'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ObjectsGet200ResponsePageInfo
     */
    'startCursor'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjectsGet200ResponsePageInfo
     */
    'endCursor'?: string;
}

