/* tslint:disable */
/* eslint-disable */
/**
 * Twenty Api
 * This is a **Twenty REST/API** playground based on the **OpenAPI 3.1 specification**.
 *
 * The version of the OpenAPI document: v0.1
 * Contact: felix@twenty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ObjectForResponse } from './object-for-response';

/**
 * 
 * @export
 * @interface ObjectsGet200ResponseData
 */
export interface ObjectsGet200ResponseData {
    /**
     * 
     * @type {Array<ObjectForResponse>}
     * @memberof ObjectsGet200ResponseData
     */
    'objects'?: Array<ObjectForResponse>;
}

