/* tslint:disable */
/* eslint-disable */
/**
 * Twenty Api
 * This is a **Twenty REST/API** playground based on the **OpenAPI 3.1 specification**.
 *
 * The version of the OpenAPI document: v0.1
 * Contact: felix@twenty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * An object
 * @export
 * @interface ObjectForUpdate
 */
export interface ObjectForUpdate {
    /**
     * 
     * @type {boolean}
     * @memberof ObjectForUpdate
     */
    'isActive'?: boolean;
}

