/* tslint:disable */
/* eslint-disable */
/**
 * Twenty Api
 * This is a **Twenty REST/API** playground based on the **OpenAPI 3.1 specification**.
 *
 * The version of the OpenAPI document: v0.1
 * Contact: felix@twenty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UpdateOneObject200ResponseData } from './update-one-object200-response-data';

/**
 * 
 * @export
 * @interface UpdateOneObject200Response
 */
export interface UpdateOneObject200Response {
    /**
     * 
     * @type {UpdateOneObject200ResponseData}
     * @memberof UpdateOneObject200Response
     */
    'data'?: UpdateOneObject200ResponseData;
}

