
# Run CI when changes are made to the admin-cli package or its internal dependencies
name: Admin CLI Dependencies CI

on:
  push:
    branches:
      - main
    paths:
      - 'packages/admin-cli/**'
      - 'packages/backend-lib/**'
      - 'packages/isomorphic-lib/**'
  pull_request:
    branches:
      - main
    paths:
      - 'packages/admin-cli/**'
      - 'packages/backend-lib/**'
      - 'packages/isomorphic-lib/**'
  workflow_dispatch:

jobs:
  admin-cli:
    uses: ./.github/workflows/shared-workflow.yaml
    with:
      package-name: 'admin-cli'
      is_backend: 'true'
      # TODO when tests are added to the admin-cli package, uncomment the following line
      # run_tests: 'true'
