# Run CI when changes are made to the API package or its internal dependencies
name: API Dependencies CI

on:
  push:
    branches:
      - main
    paths:
      - 'packages/api/**'
      - 'packages/backend-lib/**'
      - 'packages/isomorphic-lib/**'
  pull_request:
    branches:
      - main
    paths:
      - 'packages/api/**'
      - 'packages/backend-lib/**'
      - 'packages/isomorphic-lib/**'
  workflow_dispatch:

jobs:
  api:
    uses: ./.github/workflows/shared-workflow.yaml
    with:
      package-name: 'api'
      is_backend: 'true'
      run_tests: 'true'
