name: isomorphic-lib CI

on:
  push:
    branches:
      - main
    paths:
      - 'packages/isomorphic-lib/**'
  pull_request:
    branches:
      - main
    paths:
      - 'packages/isomorphic-lib/**'
  workflow_dispatch:

jobs:
  shared:
    uses: ./.github/workflows/shared-workflow.yaml
    with:
      package-name: 'isomorphic-lib'
      run_lint: 'true'
