name: Lite CI

on:
  push:
    branches:
      - main
    paths:
      - 'packages/lite/**'
  pull_request:
    branches:
      - main
    paths:
      - 'packages/lite/**'
  workflow_dispatch:

jobs:
  shared:
    uses: ./.github/workflows/shared-workflow.yaml
    with:
      package-name: 'lite'
      is_backend: 'true'
