name: Worker CI

on:
  push:
    branches:
      - main
    paths:
      - 'packages/worker/**'
  pull_request:
    branches:
      - main
    paths:
      - 'packages/worker/**'
  workflow_dispatch:

jobs:
  shared:
    uses: ./.github/workflows/shared-workflow.yaml
    with:
      package-name: 'worker'
      is_backend: 'true'
